### PR TITLE
Updating storm and kafka to latest

### PR DESCRIPTION
**Pull request by mjost5v**
Adding python script to generate sample data for UniqueVisitor
Tested with sample topologies listed in README

### CODE REVIEW

**Comment by manuzhang** [comment]
@mjost5v Thanks for PR. It may take me sometime to go through the changes. Do you know what has caused the travis failure ?

**Comment by mjost5v** [comment]
My guess would be that I was developing against Java 8 and travis is still
using Java 7. I set the compiler plugin in the pom to 1.8.

**Comment by manuzhang** [comment]
Could you upgrade travis Java version as well ?

**Comment by mjost5v** [comment]
Done. I missed the travis.yml in the initial commit. It passes now.

**Comment by manuzhang** [comment]
+1. Thanks for contribution

**Pull request merged**
